//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryModel
    {
        public int Id { get; set; }
        public string STCategoryName { get; set; }
        public string STCategoryDescription { get; set; }
        public Nullable<decimal> STPopularity { get; set; }
        public Nullable<decimal> STUnlock { get; set; }
        public Nullable<decimal> STTimeScale { get; set; }
        public Nullable<decimal> STRetention { get; set; }
        public Nullable<decimal> STIterative { get; set; }
        public string STNameGenerator { get; set; }
        public Nullable<int> SoftwareTypeModelId { get; set; }
    
        public virtual SoftwareTypeModel SoftwareTypeModel { get; set; }
    }
}
