//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependenciesList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DependenciesList()
        {
            this.FeatureDependencies = new HashSet<FeatureDependency>();
        }
    
        public int Id { get; set; }
        public string DependencySoftware { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureDependency> FeatureDependencies { get; set; }
    }
}
