//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureSoftwareCategory
    {
        public int Id { get; set; }
        public string FCName { get; set; }
        public string FCDescription { get; set; }
        public Nullable<decimal> FCPopularity { get; set; }
        public Nullable<decimal> FCTimeScale { get; set; }
        public Nullable<decimal> FCRetention { get; set; }
        public Nullable<decimal> FCIterative { get; set; }
        public string FCNameGenerator { get; set; }
        public Nullable<decimal> FCUnlock { get; set; }
    
        public virtual FeatureModel FeatureModel { get; set; }
    }
}
