//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureDependency
    {
        public int Id { get; set; }
        public string DependencySoftware { get; set; }
        public string DependencyFeature { get; set; }
    
        public virtual FeatureModel FeatureModel { get; set; }
    }
}
