//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareTypeMAttribute
    {
        public int Id { get; set; }
        public Nullable<bool> Override { get; set; }
    
        public virtual SoftwareTypeModel SoftwareTypeModels { get; set; }
    }
}
