//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareTypeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftwareTypeModel()
        {
            this.FeatureModels = new HashSet<FeatureModel>();
            this.CategoryModels = new HashSet<CategoryModel>();
        }
    
        public int Id { get; set; }
        public string RootName { get; set; }
        public string RootDescription { get; set; }
        public string RootCategory { get; set; }
        public Nullable<decimal> RootUnlock { get; set; }
        public string RootOSLimit { get; set; }
        public Nullable<bool> RootOSSpecific { get; set; }
        public Nullable<decimal> RootPopularity { get; set; }
        public Nullable<decimal> RootRandom { get; set; }
        public Nullable<decimal> RootRetention { get; set; }
        public Nullable<bool> RootOneClient { get; set; }
        public Nullable<bool> RootInHouse { get; set; }
        public Nullable<decimal> RootIterative { get; set; }
        public string RootNameGenerator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureModel> FeatureModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryModel> CategoryModels { get; set; }
        public virtual SoftwareTypeMAttribute SoftwareTypeMAttribute { get; set; }
    }
}
