//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareIncModMaker.Properties.DataSources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftwareTypeModel2Container : DbContext
    {
        public SoftwareTypeModel2Container()
            : base("name=SoftwareTypeModel2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeatureModel> FeatureModels { get; set; }
        public virtual DbSet<CategoryModel> CategoryModels { get; set; }
        public virtual DbSet<SoftwareTypeModel> SoftwareTypeModels { get; set; }
        public virtual DbSet<FeatureAttributes> FeatureAttributes { get; set; }
        public virtual DbSet<FeatureSoftwareCategory> FeatureSoftwareCategories { get; set; }
        public virtual DbSet<FeatureDependency> FeatureDependencies { get; set; }
        public virtual DbSet<SoftwareTypeMAttribute> SoftwareTypeMAttributes { get; set; }
        public virtual DbSet<DependenciesList> DependenciesLists { get; set; }
    }
}
